### ISSUE TITLE
[SWAGGER] schema difforme

### ISSUE THREAD

**Issue by wallaroo** [pagopa/issuer_integration#81]
Salve, nella definizione openapi bpd-hb-winning-api.yaml
per la chiamata 
`GET .../winning-transactions/total-cashback`
è indicato il seguente schema come ritorno della chiamata 
```
TotalScoreResource:
      title: TotalScoreResource
      required:
        - totalScore
      type: object
      properties:
        totalScore:
          type: integer
          format: int64
      description: Somma del punteggio  per la carta associata

```
ma in verità il ritorno della suddetta chiamata ha questo formato:
```
{
  "transactionNumber":0,
  "totalCashback":0
}
```
